on:
  push:
    branches: [ actions ]

name: qBittorrent WebUI App

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Dump env
        run: env | sort
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    name: Draft Release
    steps:
    - uses: actions/checkout@v2

    - run: echo ${{ github.event.release.tag_name }}

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: yarn install --pure-lockfile --non-interactive --no-progress
    - run: yarn run typecheck
    - run: yarn run build
    - run: echo $version
      env:
        CI: true
        version: ${{ github.event.release.tag_name }}
